### PR TITLE
made "home" link to the original webpage

### PR DESCRIPTION
**Pull request by ghost**
Instead of index.html, just because it looks nicer.
This probably won't work if you're testing it locally, though, but it works in production because it's tied to an actual address, which is in turn tied to a ghost html page (which is index.html in disguise).
It might work with localhost, though, if you really tried :)

### CODE REVIEW

**Comment by Kimitzuni** [comment]
I probably *should* do that, but when I build a site I just use the HTML files themselves instead of starting a local server. Because it seems completely pointless to start a server for it if I'm the only one going to be editing the files, and the files are on the machine I'm editing and viewing them on

**Comment by ghost** [comment]
ah okay.
aren't you hosting it on github though? i dont think you'd need to start a server?

**Comment by Kimitzuni** [comment]
I am, but if I'm testing it on my laptop or whatever, using a link to `/` will just take me to the system root.

**Comment by ghost** [comment]
oh okay.

**Pull request closed without merging**
